Repository travelly-8/travelly-fe, pull requests merged in 2024-05, with the labels that each got.

#7 글로벌 스타일 적용
  src/App.css
  src/App.tsx
  src/Router.tsx
  src/assets/common/arrow-left.svg
  src/assets/common/eye-off.svg
  src/assets/common/eye-on.svg
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/login/airplane.png
  src/assets/login/location.png
  src/assets/login/passport.png
  src/assets/signup/bag.png
  src/assets/signup/flash.png
  src/assets/signup/google.png
  src/assets/signup/naver.png
  src/assets/signup/signup.png
  src/components/layout/Layout.style.tsx
  src/components/layout/index.tsx
  src/index.css
  src/main.tsx
  src/styles/GlobalStyles.tsx
  src/styles/font.css
  tsconfig.json
  vite.config.ts
Labels: ⚙ Chore

#10 좌우 패딩 추가
  src/components/layout/Layout.style.tsx
Labels: ⚙ Chore

#8 글로벌 스타일 적용
  src/App.css
  src/App.tsx
  src/Router.tsx
  src/assets/common/arrow-left.svg
  src/assets/common/eye-off.svg
  src/assets/common/eye-on.svg
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/login/airplane.png
  src/assets/login/location.png
  src/assets/login/passport.png
  src/assets/signup/bag.png
  src/assets/signup/flash.png
  src/assets/signup/google.png
  src/assets/signup/naver.png
  src/assets/signup/signup.png
  src/components/layout/Layout.style.tsx
  src/components/layout/index.tsx
  src/index.css
  src/main.tsx
  src/styles/GlobalStyles.tsx
  src/styles/font.css
  tsconfig.json
  vite.config.ts
Labels: ⚙ Chore

#11 뒤로 가기 바, 시작 화면
  src/Router.tsx
  src/components/back-bar/BackBar.style.tsx
  src/components/back-bar/index.tsx
  src/pages/home/index.tsx
  src/pages/start/StartPage.style.tsx
  src/pages/start/index.tsx
Labels: ✨ Feature

#14 버튼 공통 컴포넌트
  src/components/Button/Button.style.tsx
  src/components/Button/Button.tsx
  src/components/Button/Button.type.tsx
Labels: ✨ Feature

#15 시작 화면, 회원가입 시작 및 완료 화면 UI 작업
  src/Router.tsx
  src/assets/login/bubble-left.svg
  src/assets/login/bubble-right.svg
  src/assets/login/rocket.png
  src/assets/signup/bubble.png
  src/assets/signup/naver.svg
  src/components/back-bar/BackBar.style.tsx
  src/components/icon-button/IconButton.style.tsx
  src/components/icon-button/IconButton.type.tsx
  src/components/icon-button/index.tsx
  src/components/rectangle-button/RectangleButton.style.tsx
  src/components/rectangle-button/RectangleButton.type.tsx
  src/components/rectangle-button/index.tsx
  src/pages/login/components/bubble/Bubble.style.tsx
  src/pages/login/components/bubble/Bubble.type.ts
  src/pages/login/components/bubble/index.tsx
  src/pages/login/components/confirm-page/ConfirmPage.style.tsx
  src/pages/login/components/confirm-page/index.tsx
  src/pages/login/select-plan/SelectPlanPage.style.tsx
  src/pages/login/select-plan/index.tsx
  src/pages/signup/SignupPage.style.tsx
  src/pages/signup/end/SignupEndPage.style.tsx
  src/pages/signup/end/index.tsx
  src/pages/signup/index.tsx
  src/pages/signup/splash/SplashPage.style.tsx
  src/pages/signup/splash/index.tsx
  src/pages/start/index.tsx
  src/store/modal.ts
  src/store/store.ts
  src/styles/GlobalStyles.tsx
Labels: ✨ Feature, ⚙ Chore, 🔨 Refactor

#16 타입, 인터페이스 컨벤션 반영
  src/components/icon-button/IconButton.style.tsx
  src/components/icon-button/IconButton.type.ts
  src/components/icon-button/index.tsx
  src/components/rectangle-button/RectangleButton.style.tsx
  src/components/rectangle-button/RectangleButton.type.ts
  src/components/rectangle-button/index.tsx
  src/pages/login/components/bubble/index.tsx
  src/pages/login/select-plan/index.tsx
Labels: 🔨 Refactor

#17 Input 컴포넌트
  package-lock.json
  package.json
  src/components/input/Input.style.tsx
  src/components/input/Input.type.ts
  src/components/input/index.tsx
  src/constants/INPUT_VALUES.ts
  src/utils/validate.tsx
Labels: ✨ Feature

#42 Header UI
  src/App.css
  src/App.tsx
  src/Router.tsx
  src/assets/common/alarm.svg
  src/assets/common/arrow-left.svg
  src/assets/common/eye-off.svg
  src/assets/common/eye-on.svg
  src/assets/common/kebab-click.svg
  src/assets/common/kebab.svg
  src/assets/common/search.svg
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/header/concert.svg
  src/assets/header/culture.svg
  src/assets/header/entire.svg
  src/assets/header/food.svg
  src/assets/header/leisure.svg
  src/assets/header/shop.svg
  src/assets/header/travelcourse.svg
  src/assets/header/travelspot.svg
  src/assets/login/airplane.png
  src/assets/login/location.png
  src/assets/login/passport.png
  src/assets/signup/bag.png
  src/assets/signup/flash.png
  src/assets/signup/google.png
  src/assets/signup/naver.png
  src/assets/signup/signup.png
  src/components/header/Header.style.tsx
  src/components/header/Header.type.ts
  src/components/header/index.tsx
  src/components/layout/Layout.style.tsx
  src/components/layout/index.tsx
  src/components/naviagte-button/NavigateButton.style.tsx
  src/components/naviagte-button/NavigateButton.type.ts
  src/components/naviagte-button/index.tsx
  src/index.css
  src/main.tsx
  src/pages/search/index.tsx
  src/styles/GlobalStyles.tsx
  src/styles/font.css
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature

#35 fix: 버튼 컴포넌트 오류 수정
  src/components/rectangle-button/RectangleButton.style.tsx
  src/components/rectangle-button/RectangleButton.type.ts
Labels: 🔥 Fix

#46 스타일 및 시트 상태 관리 사소한 수정
  src/components/back-bar/BackBar.style.tsx
  src/components/layout/Layout.style.tsx
  src/pages/login/components/confirm-page/index.tsx
  src/pages/login/select-plan/index.tsx
  src/store/sheet-slice.ts
  src/store/store.ts
Labels: 🔨 Refactor

#47 스쿼드 A Week1 작업
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/login/bubble-left.svg
  src/assets/login/bubble-right.svg
  src/assets/login/rocket.png
  src/assets/signup/bubble.png
  src/assets/signup/naver.svg
  src/components/back-bar/BackBar.style.tsx
  src/components/back-bar/index.tsx
  src/components/icon-button/IconButton.style.tsx
  src/components/icon-button/IconButton.type.ts
  src/components/icon-button/index.tsx
  src/components/input/Input.style.tsx
  src/components/input/Input.type.ts
  src/components/input/index.tsx
  src/components/layout/Layout.style.tsx
  src/components/rectangle-button/RectangleButton.style.tsx
  src/components/rectangle-button/RectangleButton.type.ts
  src/components/rectangle-button/index.tsx
  src/constants/INPUT_VALUES.ts
  src/pages/home/index.tsx
  src/pages/login/components/bubble/Bubble.style.tsx
  src/pages/login/components/bubble/Bubble.type.ts
  src/pages/login/components/bubble/index.tsx
  src/pages/login/components/confirm-page/ConfirmPage.style.tsx
  src/pages/login/components/confirm-page/index.tsx
  src/pages/login/select-plan/SelectPlanPage.style.tsx
  src/pages/login/select-plan/index.tsx
  src/pages/signup/SignupPage.style.tsx
  src/pages/signup/end/SignupEndPage.style.tsx
  src/pages/signup/end/index.tsx
  src/pages/signup/index.tsx
  src/pages/signup/splash/SplashPage.style.tsx
  src/pages/signup/splash/index.tsx
  src/store/sheet-slice.ts
  src/store/store.ts
  src/styles/GlobalStyles.tsx
  src/utils/validate.tsx
Labels: ✨ Feature

#44 Foldable 메뉴, 둥근 버튼 컴포넌트
  src/assets/browsing/arrow-down.svg
  src/assets/browsing/arrow-up.svg
  src/components/foldable-menu/FoldableMenu.style.tsx
  src/components/foldable-menu/FoldableMenu.type.ts
  src/components/foldable-menu/index.tsx
  src/components/range-slider/RangeSlider.styles.tsx
  src/components/range-slider/RangeSlider.type.ts
  src/components/range-slider/index.tsx
  src/components/round-button/RoundButton.style.tsx
  src/components/round-button/RoundButton.type.ts
  src/components/round-button/index.tsx
Labels: ✨ Feature

#48 FooterNavigation UI 작업 완료
  src/assets/footer-navigation/annotation-heart.svg
  src/assets/footer-navigation/bookmark.svg
  src/assets/footer-navigation/home-smile.svg
  src/assets/footer-navigation/my-page.svg
  src/assets/footer-navigation/package-plus.svg
  src/components/footer-navigation/FooterNavigation.style.tsx
  src/components/footer-navigation/FooterNavigation.type.ts
  src/components/footer-navigation/index.tsx
  src/components/navigate-button/NavigateButton.style.tsx
  src/components/navigate-button/NavigateButton.type.ts
  src/components/navigate-button/index.tsx
  src/constants/.gitkeep
  src/constants/NAVIGATE_BUTTON.ts
Labels: ✨ Feature

#49 정렬 시트 UI 작업 완료
  src/Router.tsx
  src/assets/login/bubble-left.svg
  src/assets/login/bubble-right.svg
  src/assets/login/rocket.png
  src/assets/signup/bubble.png
  src/assets/signup/naver.svg
  src/components/back-bar/BackBar.style.tsx
  src/components/back-bar/index.tsx
  src/components/icon-button/IconButton.style.tsx
  src/components/icon-button/IconButton.type.ts
  src/components/icon-button/index.tsx
  src/components/input/Input.style.tsx
  src/components/input/Input.type.ts
  src/components/input/index.tsx
  src/components/layout/Layout.style.tsx
  src/components/rectangle-button/RectangleButton.style.tsx
  src/components/rectangle-button/RectangleButton.type.ts
  src/components/rectangle-button/index.tsx
  src/constants/INPUT_VALUES.ts
  src/pages/browsing/components/sort-orders-sheet/SortOrdersSheet.style.tsx
  src/pages/browsing/components/sort-orders-sheet/index.tsx
  src/pages/browsing/index.tsx
  src/pages/home/index.tsx
  src/pages/login/components/bubble/Bubble.style.tsx
  src/pages/login/components/bubble/Bubble.type.ts
  src/pages/login/components/bubble/index.tsx
  src/pages/login/components/confirm-page/ConfirmPage.style.tsx
  src/pages/login/components/confirm-page/index.tsx
  src/pages/login/select-plan/SelectPlanPage.style.tsx
  src/pages/login/select-plan/index.tsx
  src/pages/signup/SignupPage.style.tsx
  src/pages/signup/end/SignupEndPage.style.tsx
  src/pages/signup/end/index.tsx
  src/pages/signup/index.tsx
  src/pages/signup/splash/SplashPage.style.tsx
  src/pages/signup/splash/index.tsx
  src/store/sheet-slice.ts
  src/store/store.ts
  src/styles/GlobalStyles.tsx
  src/utils/validate.tsx
Labels: ✨ Feature

#51 필터링 시트 화면, 시트 헤더
  src/assets/browsing/refresh.svg
  src/components/layout/Layout.style.tsx
  src/components/sheet-header/SheetHeader.styles.tsx
  src/components/sheet-header/SheetHeader.type.ts
  src/components/sheet-header/index.tsx
  src/pages/browsing/components/filtering-sheet/FilteringSheet.styles.tsx
  src/pages/browsing/components/filtering-sheet/index.tsx
Labels: ✨ Feature

#52 Product 카드 & Bookmark 버튼 UI 구현
  .eslintrc.cjs
  src/Router.tsx
  src/assets/browsing/bookmark-clicked.svg
  src/assets/browsing/bookmark-unclicked.svg
  src/assets/browsing/empty-star.svg
  src/assets/browsing/mock/mock-bg-1.png
  src/assets/browsing/mock/mock-bg-2.png
  src/assets/browsing/mock/mock-bg-3.png
  src/assets/browsing/mock/mock-bg-4.png
  src/assets/browsing/mock/mock-bg-5.png
  src/assets/browsing/mock/mock-bg-6.png
  src/assets/browsing/mock/mock1.png
  src/assets/browsing/mock/mock2.png
  src/assets/browsing/mock/mock3.png
  src/assets/browsing/mock/mock4.png
  src/assets/browsing/mock/mock5.png
  src/assets/browsing/mock/mock6.png
  src/components/bookmark-button/BookmarkButton.style.tsx
  src/components/bookmark-button/BookmarkButton.type.ts
  src/components/bookmark-button/index.tsx
  src/components/product-card/ProductCard.style.tsx
  src/components/product-card/ProductCard.type.ts
  src/components/product-card/index.tsx
  src/constants/MOCK_DATA.ts
  src/pages/browsing/index.tsx
Labels: ✨ Feature

#36 fix: 인풋 컴포넌트 오류 수정
  src/components/input/Input.style.tsx
  src/components/input/Input.type.ts
  src/components/input/index.tsx
  src/styles/GlobalStyles.tsx
Labels: 🔥 Fix

#39 feat: 로그인 페이지 UI 개발
  src/Router.tsx
  src/pages/login/login/index.tsx
  src/styles/authStyles.tsx
  src/utils/useKeyboardDetection.tsx
Labels: ✨ Feature

#40 feat: 회원가입 페이지 UI 개발
  src/pages/signup/signup/index.tsx
Labels: ✨ Feature

#53 달력 컴포넌트
  package-lock.json
  package.json
  src/assets/browsing/next.svg
  src/assets/browsing/previous.svg
  src/components/calendar-input/CalendarInput.styles.tsx
  src/components/calendar-input/CalendarInput.type.ts
  src/components/calendar-input/index.tsx
  src/constants/DAY_TO_STRING.ts
  src/pages/browsing/components/filtering-sheet/FilteringSheet.styles.tsx
  src/pages/browsing/components/filtering-sheet/index.tsx
Labels: ✨ Feature

#55 브라우징 페이지 UI 구현 (배너 제외)
  src/Router.tsx
  src/assets/home/arrow-down.svg
  src/assets/home/arrow-up.svg
  src/assets/home/bookmark-clicked.svg
  src/assets/home/bookmark-unclicked.svg
  src/assets/home/empty-star.svg
  src/assets/home/mock/mock-bg-1.png
  src/assets/home/mock/mock-bg-2.png
  src/assets/home/mock/mock-bg-3.png
  src/assets/home/mock/mock-bg-4.png
  src/assets/home/mock/mock-bg-5.png
  src/assets/home/mock/mock-bg-6.png
  src/assets/home/mock/mock1.png
  src/assets/home/mock/mock2.png
  src/assets/home/mock/mock3.png
  src/assets/home/mock/mock4.png
  src/assets/home/mock/mock5.png
  src/assets/home/mock/mock6.png
  src/assets/home/next.svg
  src/assets/home/previous.svg
  src/assets/home/refresh.svg
  src/assets/home/star2.svg
  src/assets/home/trophy.svg
  src/components/bookmark-button/index.tsx
  src/components/calendar-input/CalendarInput.styles.tsx
  src/components/foldable-menu/index.tsx
  src/components/footer-navigation/FooterNavigation.style.tsx
  src/components/footer-navigation/index.tsx
  src/components/header/index.tsx
  src/components/product-card/ProductCard.style.tsx
  src/components/product-card/index.tsx
  src/components/sheet-header/index.tsx
  src/constants/MOCK_DATA.ts
  src/hooks/.gitkeep
  src/pages/browsing/index.tsx
  src/pages/home/HomePage.style.tsx
  src/pages/home/components/filtering-sheet/FilteringSheet.styles.tsx
  src/pages/home/components/filtering-sheet/index.tsx
  src/pages/home/components/sort-orders-sheet/SortOrdersSheet.style.tsx
  src/pages/home/components/sort-orders-sheet/index.tsx
  src/pages/home/index.tsx
Labels: ✨ Feature

#56 Global style caution 색상변수 변경
  src/styles/GlobalStyles.tsx
Labels: 🔥 Fix

#69 회원가입 로그인 페이지 Title 레이아웃 깨짐
  src/styles/authStyles.tsx
Labels: 🔥 Fix

#62 가로 스크롤 수정
  src/components/search-sheet/SearchSheet.style.tsx
  src/components/search-sheet/index.tsx
Labels: 🔨 Refactor

#61 필터링 시트 화면
  src/components/calendar-input/index.tsx
  src/constants/DAY_TO_STRING.ts
  src/constants/FILTERING_BROWSING.ts
  src/pages/home/components/filtering-sheet/FilteringSheet.styles.tsx
  src/pages/home/components/filtering-sheet/index.tsx
Labels: ✨ Feature

#66 search sheet를 열었을 때, HomePage가 보이지 않도록 재수정
  src/Router.tsx
  src/components/footer-navigation/index.tsx
  src/components/header/index.tsx
  src/components/navigate-button/NavigateButton.style.tsx
  src/components/navigate-button/NavigateButton.type.ts
  src/components/navigate-button/index.tsx
  src/components/search-input/index.tsx
  src/components/search-sheet/PopularSearch.tsx
  src/components/search-sheet/index.tsx
  src/constants/NAVIGATE_BUTTON.ts
  src/pages/home/HomePage.style.tsx
  src/pages/home/index.tsx
  src/pages/products/ProductsPage.style.tsx
  src/pages/products/ProductsPage.type.ts
  src/pages/products/index.tsx
Labels: 🔥 Fix

#70 회원가입, 로그인 라우터 정리 및 스타일 수정
  src/Router.tsx
  src/assets/common/eye-off.svg
  src/assets/common/eye-on.svg
  src/components/input/Input.style.tsx
  src/components/input/index.tsx
  src/pages/login/login/index.tsx
  src/pages/signup/SignupStartPage.style.tsx
  src/pages/signup/index.tsx
  src/pages/signup/signup/index.tsx
  src/styles/authStyles.tsx
Labels: 🔥 Fix, 🔨 Refactor

#75 Input컴포넌트 react-hook-form적용
  package-lock.json
  package.json
  src/components/input/Input.style.tsx
  src/components/input/Input.type.ts
  src/components/input/index.tsx
  src/constants/INPUT_VALUES.ts
  src/pages/login/login/index.tsx
  src/pages/signup/signup/index.tsx
  src/styles/GlobalStyles.tsx
  src/styles/authStyles.tsx
  src/utils/validate.tsx
Labels: ✨ Feature, 🔥 Fix, 🔨 Refactor

#77 필터링 react-hook-form 적용, 초기화 기능
  src/components/calendar-input/CalendarInput.type.ts
  src/components/calendar-input/index.tsx
  src/components/range-slider/RangeSlider.type.ts
  src/components/range-slider/index.tsx
  src/pages/products/components/filtering-sheet/index.tsx
Labels: ✨ Feature

#84 axios 세팅
  src/api/axios.ts
  src/api/browsing/api.ts
Labels: 📬 API

#89 필터 적용 클릭 시 쿼리 포함 URL로 이동
  src/constants/FILTERING_BROWSING.ts
  src/pages/products/components/filtering-sheet/index.tsx
Labels: ✨ Feature, 📬 API

#78 스쿼드 A 2주차 월~수 작업
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/common/eye-off.svg
  src/assets/common/eye-on.svg
  src/components/input/Input.style.tsx
  src/components/input/Input.type.ts
  src/components/input/index.tsx
  src/constants/INPUT_VALUES.ts
  src/pages/login/login/index.tsx
  src/pages/signup/SignupStartPage.style.tsx
  src/pages/signup/index.tsx
  src/pages/signup/signup/index.tsx
  src/styles/GlobalStyles.tsx
  src/styles/authStyles.tsx
  src/utils/useKeyboardDetection.tsx
  src/utils/validate.tsx
Labels: ✨ Feature, 🔨 Refactor

#91 squad-1-B conflict 해결용 pr
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/common/eye-off.svg
  src/assets/common/eye-on.svg
  src/components/input/Input.style.tsx
  src/components/input/Input.type.ts
  src/components/input/index.tsx
  src/constants/INPUT_VALUES.ts
  src/pages/login/login/index.tsx
  src/pages/signup/SignupStartPage.style.tsx
  src/pages/signup/index.tsx
  src/pages/signup/signup/index.tsx
  src/styles/GlobalStyles.tsx
  src/styles/authStyles.tsx
  src/utils/useKeyboardDetection.tsx
  src/utils/validate.tsx
Labels: 🔥 Fix

#94 axios 기본세팅 구현
  src/api/authAPI.ts
  src/api/browsing/api.ts
  src/api/instance.ts
  src/api/myAPI.ts
  src/api/productsAPI.ts
  src/components/product-card/ProductCard.style.tsx
  src/constants/API.ts
  src/hooks/api/authAPI/.gitkeep
  src/hooks/api/productsAPI/useGetAllProducts.ts
  src/pages/home/index.tsx
  src/types/getProductData.type.ts
  src/types/postAuthData.type.ts
  src/types/postProductData.type.ts
Labels: 📬 API

#93 마이페이지 UI
  src/Router.tsx
  src/assets/common/arrow-right.svg
  src/assets/mypage/bell.svg
  src/assets/mypage/calendar.svg
  src/assets/mypage/comunity.png
  src/assets/mypage/crown.svg
  src/assets/mypage/default-profile.svg
  src/assets/mypage/review.svg
  src/assets/mypage/wallet.svg
  src/components/chip/Chip.style.tsx
  src/components/chip/index.tsx
  src/components/community-card/CommunityCard.style.tsx
  src/components/community-card/index.tsx
  src/pages/login/login/index.tsx
  src/pages/mypage/Mypage.style.tsx
  src/pages/mypage/components/community-list/CommunityList.style.tsx
  src/pages/mypage/components/community-list/index.tsx
  src/pages/mypage/components/dashboard/Dashboard.style.tsx
  src/pages/mypage/components/dashboard/Dashboard.type.ts
  src/pages/mypage/components/dashboard/index.tsx
  src/pages/mypage/components/my-product-list/MyProductList.style.tsx
  src/pages/mypage/components/my-product-list/index.tsx
  src/pages/mypage/components/mypage-header/MypageHeader.style.tsx
  src/pages/mypage/components/mypage-header/index.tsx
  src/pages/mypage/components/profile-tab/ProfileTab.style.tsx
  src/pages/mypage/components/profile-tab/index.tsx
  src/pages/mypage/components/recent-view-list/RecentViewList.style.tsx
  src/pages/mypage/components/recent-view-list/index.tsx
  src/pages/mypage/dummyData.json
  src/pages/mypage/index.tsx
  src/utils/formatWIthCommas.ts
Labels: ✨ Feature

#99 내 정보 수정 UI, 리덕스 상태 유지
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/common/bar.svg
  src/assets/mypage/exit.svg
  src/assets/mypage/key.svg
  src/assets/mypage/logout.svg
  src/assets/mypage/purple-pen.svg
  src/components/blur-sheet/BlurSheet.style.tsx
  src/components/blur-sheet/index.tsx
  src/components/bottom-sheet/BottomSheet.style.tsx
  src/components/bottom-sheet/index.tsx
  src/components/horizontal-menu/HorizontalMenu.style.tsx
  src/components/horizontal-menu/index.tsx
  src/components/input/Input.style.tsx
  src/components/input/Input.type.ts
  src/components/input/index.tsx
  src/components/page-header/PageHeader.style.tsx
  src/components/page-header/index.tsx
  src/components/sheet-header/SheetHeader.type.ts
  src/components/sheet-header/index.tsx
  src/constants/INPUT_VALUES.ts
  src/main.tsx
  src/pages/login/select-plan/index.tsx
  src/pages/mypage/Mypage.style.tsx
  src/pages/mypage/components/dashboard/Dashboard.style.tsx
  src/pages/mypage/components/edit-password/EditPasswordPage.style.tsx
  src/pages/mypage/components/edit-password/index.tsx
  src/pages/mypage/components/mypage-header/MypageHeader.style.tsx
  src/pages/mypage/components/mypage-header/index.tsx
  src/pages/mypage/components/profile-tab/ProfileTab.style.tsx
  src/pages/mypage/components/profile-tab/index.tsx
  src/pages/mypage/edit/MyPageEditPage.style.tsx
  src/pages/mypage/edit/index.tsx
  src/pages/mypage/exit-verification/ExitVerification.style.tsx
  src/pages/mypage/exit-verification/index.tsx
  src/pages/mypage/exit/ExitPage.style.tsx
  src/pages/mypage/exit/index.tsx
  src/pages/mypage/good-bye/GoodbyPage.style.tsx
  src/pages/mypage/good-bye/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/signup/index.tsx
  src/store/sheet-slice.ts
  src/store/store.ts
Labels: ✨ Feature, 🔥 Fix, 🔨 Refactor
