Repository travelly-8/travelly-fe, pull requests merged in 2024-06, with the labels that each got.

#96 ProductCard api 연결 작업
  src/api/authAPI.ts
  src/api/browsing/api.ts
  src/api/instance.ts
  src/api/myAPI.ts
  src/api/productsAPI.ts
  src/components/header/Header.style.tsx
  src/components/header/index.tsx
  src/components/product-card/ProductCard.style.tsx
  src/components/product-card/ProductCard.type.ts
  src/components/product-card/index.tsx
  src/components/product-header/ProductHeader.style.tsx
  src/components/product-header/index.tsx
  src/components/search-sheet/index.tsx
  src/constants/API.ts
  src/constants/FILTERING_BROWSING.ts
  src/hooks/api/authAPI/.gitkeep
  src/hooks/api/productsAPI/useGetAllProducts.ts
  src/pages/home/HomePage.style.tsx
  src/pages/home/HomePage.type.ts
  src/pages/home/index.tsx
  src/pages/products/ProductsPage.style.tsx
  src/pages/products/index.tsx
  src/types/.gitkeep
  src/types/getProductData.type.ts
  src/types/postAuthData.type.ts
  src/types/postProductData.type.ts
  src/utils/registerLocalStorage.ts
Labels: 📬 API

#100 검색, 카테고리별, 필터링, 정렬 api 연결
  src/api/productsAPI.ts
  src/constants/API.ts
  src/hooks/api/productsAPI/useGetSearchProducts.ts
  src/pages/products/components/filtering-sheet/index.tsx
  src/pages/products/components/sort-orders-sheet/index.tsx
  src/pages/products/index.tsx
  src/types/postProductData.type.ts
Labels: 📬 API

#102 Choi#92/squad b api
  src/api/productsAPI.ts
  src/components/product-card/ProductCard.type.ts
  src/components/product-card/index.tsx
  src/constants/API.ts
  src/hooks/api/productsAPI/useGetSearchProducts.ts
  src/pages/products/components/filtering-sheet/index.tsx
  src/pages/products/components/sort-orders-sheet/index.tsx
  src/pages/products/index.tsx
  src/types/getProductData.type.ts
  src/types/postProductData.type.ts
Labels: 🔥 Fix, 📬 API

#101 products페이지 무한스크롤 적용
  src/Router.tsx
  src/components/product-card/ProductCard.style.tsx
  src/components/product-card/index.tsx
  src/components/product-header/index.tsx
  src/constants/PRODUCT_TYPE.ts
  src/hooks/api/productsAPI/useInfiniteCardsQuery.ts
  src/hooks/useIntersectionObserver.ts
  src/pages/home/index.tsx
  src/pages/products/ProductsPage.style.tsx
  src/pages/products/index.tsx
  src/utils/registerLocalStorage.ts
Labels: ✨ Feature, 📬 API

#105 로그인 회원가입 navigate 추가
  src/pages/login/components/bubble/index.tsx
  src/pages/login/select-plan/index.tsx
  src/pages/signup/end/index.tsx
  src/pages/signup/signup/index.tsx
Labels: ✨ Feature, 🔥 Fix

#107 로그인 회원가입 API관련 리팩토링
  src/Router.tsx
  src/components/form-container/FormContainer.type.ts
  src/components/form-container/index.tsx
  src/constants/INPUT_VALUES.ts
  src/hooks/useFormValidation.ts
  src/pages/auth/index.tsx
  src/pages/login/components/confirm-page/index.tsx
  src/pages/login/login/Login.type.ts
  src/pages/login/login/index.tsx
  src/pages/login/select-plan/index.tsx
  src/pages/signup/index.tsx
  src/pages/signup/signup/Signup.type.ts
  src/pages/signup/signup/index.tsx
  src/utils/validate.tsx
Labels: ✨ Feature, 🔥 Fix, 📬 API, 🔨 Refactor

#106 마이페이지 - 내 정보 수정 API 연결
  src/api/myAPI.ts
  src/api/productsAPI.ts
  src/constants/API.ts
  src/hooks/api/memberAPI/useGetMemberProfile.ts
  src/hooks/api/productsAPI/useGetSearchProducts.ts
  src/pages/mypage/components/edit-password/EditPasswordPage.style.tsx
  src/pages/mypage/components/edit-password/index.tsx
  src/pages/mypage/edit/index.tsx
  src/pages/products/components/filtering-sheet/index.tsx
  src/pages/products/components/sort-orders-sheet/index.tsx
  src/pages/products/index.tsx
  src/types/getMemberData.type.ts
  src/types/postProductData.type.ts
  src/types/putMemberData.type.ts
Labels: ✨ Feature

#109 Form container 타입에러 수정
  src/components/form-container/index.tsx
Labels: 🔥 Fix

#110 프리티어 적용 안되던 부분 문제 해결
  .github/ISSUE_TEMPLATE/✅-feature.md
  package-lock.json
  package.json
  src/Router.tsx
  src/api/authAPI.ts
  src/api/instance.ts
  src/components/form-container/index.tsx
  src/hooks/useFormValidation.ts
  src/pages/auth/index.tsx
  src/pages/login/components/confirm-page/index.tsx
  src/pages/login/login/index.tsx
  src/pages/login/select-plan/index.tsx
  src/pages/signup/end/index.tsx
  src/pages/signup/signup/index.tsx
  src/utils/tokenStorage.ts
Labels: 🔥 Fix

#111 필터링 default값 수정, 이미지 캐러셀 컴포넌트
  src/components/image-carousel/ImageCarousel.styles.tsx
  src/components/image-carousel/ImageCarousel.type.ts
  src/components/image-carousel/index.tsx
  src/constants/MOCK_DATA.ts
  src/pages/products/components/filtering-sheet/index.tsx
Labels: ✨ Feature

#113 [스쿼드 B] 2주차 작업
  src/Router.tsx
  src/api/.gitkeep
  src/assets/home/bookmark-clicked.svg
  src/assets/home/mock/mock-bg-1.png
  src/assets/home/mock/mock-bg-2.png
  src/assets/home/mock/mock-bg-3.png
  src/assets/home/mock/mock-bg-4.png
  src/assets/home/mock/mock-bg-5.png
  src/assets/home/mock/mock-bg-6.png
  src/assets/home/mock/mock1.png
  src/assets/home/mock/mock2.png
  src/assets/home/mock/mock3.png
  src/assets/home/mock/mock4.png
  src/assets/home/mock/mock5.png
  src/assets/home/mock/mock6.png
  src/components/back-bar/index.tsx
  src/components/bookmark-button/index.tsx
  src/components/header/Header.style.tsx
  src/components/header/index.tsx
  src/components/image-carousel/ImageCarousel.styles.tsx
  src/components/image-carousel/ImageCarousel.type.ts
  src/components/image-carousel/index.tsx
  src/components/product-card/ProductCard.style.tsx
  src/components/product-card/ProductCard.type.ts
  src/components/product-card/index.tsx
  src/components/product-header/ProductHeader.style.tsx
  src/components/product-header/index.tsx
  src/components/search-sheet/index.tsx
  src/constants/FILTERING_BROWSING.ts
  src/constants/MOCK_DATA.ts
  src/constants/PRODUCT_TYPE.ts
  src/hooks/api/productsAPI/useInfiniteCardsQuery.ts
  src/hooks/api/productsAPI/useProductCardsParams.ts
  src/hooks/useIntersectionObserver.ts
  src/pages/home/HomePage.style.tsx
  src/pages/home/HomePage.type.ts
  src/pages/home/index.tsx
  src/pages/products/ProductsPage.style.tsx
  src/pages/products/ProductsPage.type.ts
  src/pages/products/components/app-bar/AppBar.style.tsx
  src/pages/products/components/app-bar/AppBar.type.ts
  src/pages/products/components/app-bar/index.tsx
  src/pages/products/components/filtering-sheet/index.tsx
  src/pages/products/index.tsx
  src/types/getProductData.type.ts
  src/utils/registerLocalStorage.ts
Labels: ✨ Feature, 📬 API

#115 배포 에러 수정
  src/components/sheet-header/SheetHeader.type.ts
  src/pages/mypage/index.tsx
  src/pages/signup/signup/index.tsx
Labels: 🌏 Deploy

#116 fix: 배포 라우터 새로고침 에러
  vercel.json
Labels: 🌏 Deploy, 🔥 Fix

#119 result 페이지 라우팅, 상세 페이지 하단 footer
  src/Router.tsx
  src/components/bookmark-button/BookmarkButton.type.ts
  src/components/bookmark-button/index.tsx
  src/components/round-button/RoundButton.style.tsx
  src/components/round-button/index.tsx
  src/pages/result/components/footer/Footer.style.tsx
  src/pages/result/components/footer/Footer.type.ts
  src/pages/result/components/footer/index.tsx
  src/pages/result/index.tsx
Labels: ✨ Feature

#121 추천 상품 목록, 상세 페이지 편집 시트
  src/components/product-card/ProductCard.style.tsx
  src/components/product-card/ProductCard.type.ts
  src/components/product-card/index.tsx
  src/pages/result/components/edit-sheet/EditSheet.styles.tsx
  src/pages/result/components/edit-sheet/index.tsx
  src/pages/result/components/recommend-card/RecommendCard.styles.tsx
  src/pages/result/components/recommend-card/index.tsx
  src/pages/result/index.tsx
Labels: ✨ Feature

#128 역할 선택 클릭 이벤트 오류 수정
  src/pages/login/select-plan/index.tsx
Labels: 🔥 Fix

#129 리뷰 상품 리스트 공통 컴포넌트
  .github/workflows/main.yml
  build.sh
  src/Router.tsx
  src/components/sheet-header/SheetHeader.type.ts
  src/pages/review/components/review-product-card/ReviewProductCard.style.tsx
  src/pages/review/components/review-product-card/index.tsx
  src/pages/review/write/ReviewWritePage.style.tsx
  src/pages/review/write/index.tsx
  src/pages/signup/signup/index.tsx
  vercel.json
Labels: ✨ Feature

#132 로그인 회원가입 관련 페이지 콘솔 에러 수정
  src/components/icon-button/IconButton.style.tsx
  src/components/icon-button/index.tsx
  src/components/input/Input.style.tsx
  src/components/input/Input.type.ts
  src/components/input/index.tsx
  src/main.tsx
  src/pages/login/select-plan/index.tsx
  src/store/store.ts
Labels: 🔥 Fix, 🔨 Refactor

#130 제품 상세 ui
  src/Router.tsx
  src/api/authAPI.ts
  src/assets/productsdetail/comment.svg
  src/assets/productsdetail/edit.svg
  src/assets/productsdetail/ex1.png
  src/assets/productsdetail/like.svg
  src/assets/productsdetail/location.svg
  src/assets/productsdetail/share.svg
  src/assets/productsdetail/sort.svg
  src/assets/productsdetail/star.svg
  src/assets/productsdetail/starex.svg
  src/components/layout/Layout.style.tsx
  src/constants/API.ts
  src/pages/productsdetail/ProductsDetail.style.tsx
  src/pages/productsdetail/components/basicinfo/BasicInfo.style.tsx
  src/pages/productsdetail/components/basicinfo/BasicInfo.type.ts
  src/pages/productsdetail/components/basicinfo/index.tsx
  src/pages/productsdetail/components/description/Description.style.tsx
  src/pages/productsdetail/components/description/index.tsx
  src/pages/productsdetail/components/edit-sheet/EditSheet.styles.tsx
  src/pages/productsdetail/components/edit-sheet/index.tsx
  src/pages/productsdetail/components/footer/Footer.style.tsx
  src/pages/productsdetail/components/footer/Footer.type.ts
  src/pages/productsdetail/components/footer/index.tsx
  src/pages/productsdetail/components/info/Info.style.tsx
  src/pages/productsdetail/components/info/Info.type.ts
  src/pages/productsdetail/components/info/index.tsx
  src/pages/productsdetail/components/recommend-card/RecommendCard.styles.tsx
  src/pages/productsdetail/components/recommend-card/index.tsx
  src/pages/productsdetail/components/review/Review.style.tsx
  src/pages/productsdetail/components/review/Review.type.ts
  src/pages/productsdetail/components/review/ReviewPage.tsx
  src/pages/productsdetail/components/review/index.tsx
  src/pages/productsdetail/index.tsx
  src/pages/productsdetail/mockdata.ts
  src/pages/result/index.tsx
Labels: ✨ Feature

#138 회원 유형 선택 페이지 : 접근 권한에 따른 분기 처리
  src/Router.tsx
  src/pages/login/components/confirm-page/index.tsx
  src/pages/login/login/index.tsx
  src/router/SelectPlanRouter.tsx
  src/store/store.ts
  src/store/user-slice.ts
Labels: 🔥 Fix

#139 수정 시트 연결
  src/assets/common/hamburger-click.svg
  src/assets/common/hamburger.svg
  src/assets/common/kebab.svg
  src/components/header/Header.type.ts
  src/components/header/index.tsx
  src/components/product-header/ProductHeader.type.ts
  src/components/product-header/index.tsx
  src/pages/home/HomePage.style.tsx
  src/pages/home/index.tsx
  src/pages/products-detail/components/edit-sheet/EditSheet.styles.tsx
  src/pages/products-detail/components/edit-sheet/index.tsx
  src/pages/products-detail/components/review/Review.style.tsx
  src/pages/products-detail/components/review/Review.type.ts
  src/pages/products-detail/components/review/ReviewPage.tsx
  src/pages/products-detail/components/review/index.tsx
  src/pages/products-detail/index.tsx
  src/pages/products/index.tsx
Labels: ✨ Feature

#140 배포 환경에서 이미지 나타나지 않는 오류 수정
  src/components/back-bar/index.tsx
  src/components/product-card/index.tsx
  src/pages/home/index.tsx
  src/pages/login/components/confirm-page/index.tsx
  src/pages/login/select-plan/index.tsx
  src/pages/mypage/good-bye/index.tsx
  src/pages/products/components/app-bar/index.tsx
  src/pages/signup/end/index.tsx
  src/pages/signup/index.tsx
  tsconfig.json
Labels: 🔥 Fix

#143 후기 리스트 페이지 UI
  src/Router.tsx
  src/pages/auth/index.tsx
  src/pages/login/login/index.tsx
  src/pages/login/select-plan/index.tsx
  src/pages/review/components/review-product-card/ReviewProductCard.style.tsx
  src/pages/review/components/review-product-card/index.tsx
  src/pages/review/list/ReviewList.style.tsx
  src/pages/review/list/ReviewList.type.ts
  src/pages/review/list/index.tsx
  src/pages/review/write/ReviewWritePage.style.tsx
  src/store/authSlice.ts
  src/store/store.ts
Labels: ✨ Feature, 🔥 Fix

#145 카카오톡 공유기능 & 클립보드 복사
  .gitignore
  index.html
  kakao.d.ts
  src/Router.tsx
  src/components/product-card/ProductCard.style.tsx
  src/components/product-card/index.tsx
  src/pages/login/components/confirm-page/index.tsx
  src/pages/products-detail/components/share-sheet/ShareSheet.type.ts
  src/pages/products-detail/components/share-sheet/index.tsx
  src/pages/products-detail/index.tsx
  src/utils/kakaoShare.ts
Labels: ✨ Feature

#147 후기사진 모아보기 UI
  src/pages/login/components/confirm-page/index.tsx
  src/pages/products-detail/ProductsDetail.style.tsx
  src/pages/products-detail/components/photo-reviews-sheet/PhotoReviewsSheet.styles.tsx
  src/pages/products-detail/components/photo-reviews-sheet/index.tsx
  src/pages/products-detail/components/review/Review.style.tsx
  src/pages/products-detail/components/review/Review.type.ts
  src/pages/products-detail/components/review/index.tsx
  src/pages/products-detail/index.tsx
Labels: ✨ Feature

#150 회원 유형 선택 부분 refactoring
  src/pages/login/components/confirm-page/index.tsx
  src/pages/login/login/index.tsx
  src/pages/login/select-plan/index.tsx
  src/pages/signup/signup/index.tsx
  src/router/SelectPlanRouter.tsx
  src/store/auth-slice.ts
  src/store/store.ts
  src/store/user-slice.ts
  src/types/userRole.type.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#152 상세 페이지 api 연결 작업
  src/Router.tsx
  src/api/productsAPI.ts
  src/components/bookmark-button/BookmarkButton.type.ts
  src/components/product-card/ProductCard.style.tsx
  src/components/product-card/index.tsx
  src/constants/API.ts
  src/constants/FILTERING_BROWSING.ts
  src/pages/products-detail/ProductsDetail.type.ts
  src/pages/products-detail/components/basic-info/index.tsx
  src/pages/products-detail/components/info/Info.style.tsx
  src/pages/products-detail/components/info/index.tsx
  src/pages/products-detail/components/recommend-card/index.tsx
  src/pages/products-detail/components/review/Review.style.tsx
  src/pages/products-detail/components/share-sheet/ShareSheet.style.tsx
  src/pages/products-detail/components/sheet-renderer/SheetRenderer.type.ts
  src/pages/products-detail/components/sheet-renderer/index.tsx
  src/pages/products-detail/index.tsx
  src/utils/kakaoShare.ts
Labels: ✨ Feature, 📬 API

#153 정렬 에러 해결
  src/constants/FILTERING_BROWSING.ts
  src/hooks/api/productsAPI/useInfiniteCardsQuery.ts
  src/hooks/api/productsAPI/useProductCardsParams.ts
  src/pages/products/components/card-orders-sheet/index.tsx
  src/types/postProductData.type.ts
Labels: 🔥 Fix

#154 default image, 리뷰 사진, 추천 상품
  src/components/image-carousel/index.tsx
  src/components/product-card/ProductCard.style.tsx
  src/components/product-card/index.tsx
  src/pages/products-detail/components/review/Review.type.ts
  src/pages/products-detail/components/review/ReviewPage.tsx
  src/pages/products-detail/components/review/index.tsx
  src/pages/products-detail/index.tsx
  src/pages/products-detail/mockData.ts
Labels: ✨ Feature, 📬 API

#156 마이페이지 API 연결
  src/Router.tsx
  src/api/authAPI.ts
  src/api/myAPI.ts
  src/constants/API.ts
  src/pages/mypage/edit/index.tsx
  src/pages/mypage/exit-verification/index.tsx
  src/pages/review/detail/ReviewDetailPage.style.tsx
  src/pages/review/detail/index.tsx
  src/utils/tokenStorage.ts
Labels: ✨ Feature, 📬 API

#159 product 카드에 스켈레톤 ui 적용
  src/components/product-card/ProductCard.style.tsx
  src/components/product-card/ProductCard.type.ts
  src/components/product-card/ProductCardSkeleton.tsx
  src/components/product-card/index.tsx
  src/hooks/api/productsAPI/useInfiniteCardsQuery.ts
  src/pages/home/HomePage.type.ts
  src/pages/home/index.tsx
  src/pages/products-detail/index.tsx
  src/pages/products/index.tsx
Labels: ✨ Feature

#157 [스쿼드 A] 3주차 금~일 작업
  src/Router.tsx
  src/api/authAPI.ts
  src/api/myAPI.ts
  src/constants/API.ts
  src/pages/auth/index.tsx
  src/pages/login/components/confirm-page/index.tsx
  src/pages/login/login/index.tsx
  src/pages/login/select-plan/index.tsx
  src/pages/mypage/edit/index.tsx
  src/pages/mypage/exit-verification/index.tsx
  src/pages/review/components/review-product-card/ReviewProductCard.style.tsx
  src/pages/review/components/review-product-card/index.tsx
  src/pages/review/detail/ReviewDetailPage.style.tsx
  src/pages/review/detail/index.tsx
  src/pages/review/list/ReviewList.style.tsx
  src/pages/review/list/ReviewList.type.ts
  src/pages/review/list/index.tsx
  src/pages/review/write/ReviewWritePage.style.tsx
  src/pages/signup/signup/index.tsx
  src/router/SelectPlanRouter.tsx
  src/store/auth-slice.ts
  src/store/store.ts
  src/store/user-slice.ts
  src/types/userRole.type.ts
  src/utils/tokenStorage.ts
Labels: ✨ Feature, 🔥 Fix, 📬 API, 🔨 Refactor

#165 [스쿼드 B] 3주차 금~일 작업
  .gitignore
  index.html
  kakao.d.ts
  src/Router.tsx
  src/api/productsAPI.ts
  src/components/bookmark-button/BookmarkButton.type.ts
  src/components/image-carousel/index.tsx
  src/components/product-card/ProductCard.style.tsx
  src/components/product-card/ProductCard.type.ts
  src/components/product-card/ProductCardSkeleton.tsx
  src/components/product-card/index.tsx
  src/constants/API.ts
  src/constants/FILTERING_BROWSING.ts
  src/hooks/api/productsAPI/useInfiniteCardsQuery.ts
  src/hooks/api/productsAPI/useProductCardsParams.ts
  src/pages/home/HomePage.type.ts
  src/pages/home/index.tsx
  src/pages/login/components/confirm-page/index.tsx
  src/pages/products-detail/ProductsDetail.style.tsx
  src/pages/products-detail/ProductsDetail.type.ts
  src/pages/products-detail/components/basic-info/index.tsx
  src/pages/products-detail/components/info/Info.style.tsx
  src/pages/products-detail/components/info/index.tsx
  src/pages/products-detail/components/photo-reviews-sheet/PhotoReviewsSheet.styles.tsx
  src/pages/products-detail/components/photo-reviews-sheet/index.tsx
  src/pages/products-detail/components/recommend-card/index.tsx
  src/pages/products-detail/components/review/Review.style.tsx
  src/pages/products-detail/components/review/Review.type.ts
  src/pages/products-detail/components/review/ReviewPage.tsx
  src/pages/products-detail/components/review/index.tsx
  src/pages/products-detail/components/share-sheet/ShareSheet.style.tsx
  src/pages/products-detail/components/share-sheet/ShareSheet.type.ts
  src/pages/products-detail/components/share-sheet/index.tsx
  src/pages/products-detail/components/sheet-renderer/SheetRenderer.type.ts
  src/pages/products-detail/components/sheet-renderer/index.tsx
  src/pages/products-detail/index.tsx
  src/pages/products-detail/mockData.ts
  src/pages/products/components/card-orders-sheet/index.tsx
  src/pages/products/index.tsx
  src/types/postProductData.type.ts
  src/utils/kakaoShare.ts
Labels: ✨ Feature, 🔥 Fix, 📬 API

#166 bookmarkButton 타입 에러 해결
  src/components/bookmark-button/BookmarkButton.style.tsx
  src/components/bookmark-button/BookmarkButton.type.ts
  src/components/bookmark-button/index.tsx
  src/components/product-card/index.tsx
Labels: 🔥 Fix

#181 예약 input 컴포넌트
  .eslintrc.cjs
  src/components/search-sheet/SearchSheet.style.tsx
  src/pages/reservation/components/reservation-input/Reservation.type.ts
  src/pages/reservation/components/reservation-input/ReservationInput.style.tsx
  src/pages/reservation/components/reservation-input/index.tsx
  src/styles/GlobalStyles.tsx
Labels: ✨ Feature

#183 예약 페이지에 필요한 각종 시트
  src/components/grab-sheet/GrabSheet.style.tsx
  src/components/grab-sheet/GrabSheet.type.ts
  src/components/grab-sheet/index.tsx
  src/components/range-calendar-input/RangeCalendarInput.styles.tsx
  src/components/range-calendar-input/index.tsx
  src/pages/reservation/components/sheet/PaySheet.styles.tsx
  src/pages/reservation/components/sheet/PaySheet.type.ts
  src/pages/reservation/components/sheet/calendar-sheet/CalendarSheet.styles.tsx
  src/pages/reservation/components/sheet/calendar-sheet/index.tsx
  src/pages/reservation/components/sheet/pay-cancel-sheet/index.tsx
  src/pages/reservation/components/sheet/pay-confirm-sheet/index.tsx
  src/utils/makeKORLocale.ts
Labels: ✨ Feature

#189 후기 api연결 관련 상품상세 리팩토링
  kakao.maps.d.ts
  src/api/reviewAPI.ts
  src/components/footer-button/FooterButton.style.tsx
  src/components/footer-button/index.tsx
  src/components/grab-sheet/index.tsx
  src/components/header/index.tsx
  src/components/product-header/index.tsx
  src/components/review-product-card/ReviewProductCard.style.tsx
  src/components/review-product-card/ReviewProductCard.type.ts
  src/components/review-product-card/index.tsx
  src/components/search-sheet/index.tsx
  src/components/sheet-header/index.tsx
  src/constants/REVIEW.ts
  src/pages/auth/index.tsx
  src/pages/home/index.tsx
  src/pages/login/components/confirm-page/index.tsx
  src/pages/login/login/index.tsx
  src/pages/login/select-plan/index.tsx
  src/pages/mypage/edit/index.tsx
  src/pages/mypage/exit/index.tsx
  src/pages/products-detail/components/info/Info.type.ts
  src/pages/products-detail/components/review/Review.style.tsx
  src/pages/products-detail/components/review/Review.type.ts
  src/pages/products-detail/components/review/index.tsx
  src/pages/products-detail/components/sheet-renderer/SheetRenderer.type.ts
  src/pages/products-detail/components/sheet-renderer/index.tsx
  src/pages/products-detail/index.tsx
  src/pages/products/components/card-orders-sheet/index.tsx
  src/pages/products/components/filtering-sheet/index.tsx
  src/pages/products/index.tsx
  src/pages/review/components/comment-card/index.tsx
  src/pages/review/components/rating/Rating.style.tsx
  src/pages/review/components/rating/Rating.type.ts
  src/pages/review/components/rating/index.tsx
  src/pages/review/components/review-product-card/index.tsx
  src/pages/review/detail/index.tsx
  src/pages/review/list/ReviewList.type.ts
  src/pages/review/list/Skeleton.style.ts
  src/pages/review/list/index.tsx
  src/pages/review/write/index.tsx
  src/store/auth-slice/auth-slice.ts
  src/store/auth-slice/auth-slice.type.ts
  src/store/product-slice/product-slice.ts
  src/store/product-slice/product-slice.type.ts
  src/store/sheet-slice/sheet-slice.ts
  src/store/sheet-slice/sheet-slice.type.ts
  src/store/store.ts
  tsconfig.json
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#190 카카오맵 타입 오류 해결
  kakao.maps.d.ts
  src/hooks/useKakaoMap.ts
Labels: 🔥 Fix

#192 카카오맵, 카카오 공유 타입 에러 수정
  kakao.d.ts
  src/pages/products-detail/components/basic-info/index.tsx
  src/pages/products-detail/components/share-sheet/index.tsx
  src/pages/products-detail/index.tsx
  src/utils/kakaoShare.ts
Labels: 🔥 Fix

#200 deboucing 추천검색어 구현
  package-lock.json
  package.json
  src/components/search-input/RecommendedSearches.tsx
  src/components/search-input/SearchInput.style.tsx
  src/components/search-input/index.tsx
  src/utils/shuffleArray.ts
Labels: ✨ Feature, 📬 API

#199 후기 상세 데이터 연결, 댓글 작성
  src/Router.tsx
  src/api/reviewAPI.ts
  src/constants/API.ts
  src/hooks/api/reviewAPI/useGetReviewDetail.ts
  src/pages/products-detail/components/review/Review.type.ts
  src/pages/products-detail/components/review/ReviewPage.tsx
  src/pages/products-detail/components/review/index.tsx
  src/pages/products-detail/index.tsx
  src/pages/review/components/comment-card/CommentCard.style.tsx
  src/pages/review/components/comment-card/index.tsx
  src/pages/review/detail/ReviewDetailPage.style.tsx
  src/pages/review/detail/index.tsx
  src/store/comment-slice/comment-slice.ts
  src/store/comment-slice/comment-slice.type.ts
  src/store/store.ts
  src/types/getReviewDetailData.type.ts
  src/types/postCommentData.type.ts
Labels: 📬 API

#206 상품 상세 후기 컴포넌트 타입 에러 & baseUrl 변경
  src/api/axios.ts
  src/pages/products-detail/components/review/index.tsx
  src/pages/review/detail/ReviewDetailPage.style.tsx
  src/pages/review/detail/index.tsx
Labels: 🔥 Fix

#207 product-detail 페이지 이미지, 날짜 api 연결 & 카카오 공유하기 오류 해결
  kakao.d.ts
  src/components/image-carousel/ImageCarousel.type.ts
  src/components/image-carousel/index.tsx
  src/pages/products-detail/ProductsDetail.type.ts
  src/pages/products-detail/components/info/Info.type.ts
  src/pages/products-detail/components/info/index.tsx
  src/pages/products-detail/components/review/Review.type.ts
  src/pages/products-detail/components/share-sheet/index.tsx
  src/pages/products-detail/index.tsx
  src/store/product-slice/product-slice.ts
  src/store/product-slice/product-slice.type.ts
  src/types/postProductData.type.ts
  src/utils/formatDate.ts
Labels: ✨ Feature, 🔥 Fix, 📬 API

#208 예약 정보 확인 페이지
  src/Router.tsx
  src/components/footer-reservation/FooterReservation.type.ts
  src/components/footer-reservation/index.tsx
  src/pages/products-detail/ProductsDetail.type.ts
  src/pages/products-detail/components/sheet-renderer/SheetRenderer.type.ts
  src/pages/products-detail/components/sheet-renderer/index.tsx
  src/pages/reservation/components/cancellation-policy/CancellationPolicy.style.tsx
  src/pages/reservation/components/sheet/pay-cancel-sheet/index.tsx
  src/pages/reservation/components/ticket-count-section/index.tsx
  src/pages/reservation/reserve/index.tsx
  src/pages/reservation/reserved-detail/ReservedDetailPage.syles.tsx
  src/pages/reservation/reserved-detail/index.tsx
Labels: ✨ Feature

#210 모든 날짜 데이터값도 리턴할 수 있도록 수정 & axios base Url 변경
  src/api/fileInstance.ts
  src/api/instance.ts
  src/pages/products-detail/components/info/index.tsx
  src/utils/formatDate.ts
Labels: 🔨 Refactor

#218 baseURL 변경
  src/api/axios.ts
  src/api/fileInstance.ts
  src/api/instance.ts
  src/constants/API.ts
Labels: 📬 API

#209 예약 페이지 api연동 및 예약 페이지 기능 추가
  src/components/check-box/index.tsx
  src/components/footer-reservation/FooterReservation.type.ts
  src/components/footer-reservation/index.tsx
  src/pages/reservation/components/cancellation-policy/index.tsx
  src/pages/reservation/components/reservation-input/Reservation.type.ts
  src/pages/reservation/components/reservation-input/index.tsx
  src/pages/reservation/components/ticket-count-section/index.tsx
  src/pages/reservation/reserve/index.tsx
  src/store/personnel-slice/personnel-slice.ts
  src/store/personnel-slice/personnel-slice.type.ts
  src/store/store.ts
  vite.config.ts
Labels: ✨ Feature, 📬 API

#226 상세, 후기 연결 & 추천 관광지 api 연결 & 예약 날짜 선택
  src/assets/common/default-user.svg
  src/pages/products-detail/components/recommend-card/index.tsx
  src/pages/products-detail/components/review/ReviewPage.tsx
  src/pages/products-detail/components/review/index.tsx
  src/pages/products-detail/components/sheet-renderer/SheetRenderer.type.ts
  src/pages/products-detail/components/sheet-renderer/index.tsx
  src/pages/products-detail/index.tsx
  src/pages/reservation/components/reservation-date-section/index.tsx
  src/pages/reservation/components/reservation-input/Reservation.type.ts
  src/pages/reservation/components/sheet/calendar-sheet/index.tsx
  src/pages/reservation/reserve/index.tsx
  src/pages/review/components/comment-card/index.tsx
Labels: ✨ Feature, 🔥 Fix, 📬 API

#215 상품 등록, 리스트 UI & FNB 분기 처리
  src/Router.tsx
  src/assets/common/arrow-right-lightgray.svg
  src/assets/common/camera.svg
  src/components/footer-navigation/index.tsx
  src/components/input/Input.style.tsx
  src/components/input/Input.type.ts
  src/components/input/index.tsx
  src/components/page-header/PageHeader.style.tsx
  src/components/page-header/index.tsx
  src/components/product-card/ProductCard.type.ts
  src/components/product-card/index.tsx
  src/constants/INPUT_VALUES.ts
  src/constants/NAVIGATE_BUTTON.ts
  src/pages/mypage/components/my-product/MyProduct.style.tsx
  src/pages/mypage/components/my-product/index.tsx
  src/pages/mypage/components/profile-tab/ProfileTab.style.tsx
  src/pages/mypage/components/recent-view-list/index.tsx
  src/pages/mypage/dummyData.json
  src/pages/mypage/edit/MyPageEditPage.style.tsx
  src/pages/mypage/edit/index.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/my-product-list/MyProductListPage.style.tsx
  src/pages/mypage/my-product-list/index.tsx
  src/pages/products-create/ProductsCreatePage.style.tsx
  src/pages/products-create/index.tsx
  src/pages/products/components/app-bar/AppBar.type.ts
  src/pages/products/components/app-bar/index.tsx
  src/pages/signup/SignupStartPage.style.tsx
  src/pages/signup/index.tsx
  src/router/SplashRouter.tsx
  src/types/userRole.type.ts
Labels: ✨ Feature, 🔥 Fix, 🔨 Refactor

#216 체험상품 관리 페이지 UI 작업
  src/assets/products-create/shoppingCart.svg
  src/components/rectangle-button/RectangleButton.style.tsx
  src/pages/products-create/components/ReservationCard/ReservationCard.style.tsx
  src/pages/products-create/components/ReservationCard/ReservationCard.type.ts
  src/pages/products-create/components/ReservationCard/index.tsx
  src/pages/products-create/components/ReservationCard/mockData.ts
  src/pages/products-create/components/ReservationCardButtonContainer/ReservationCardButtonContainer.style.ts
  src/pages/products-create/components/ReservationCardButtonContainer/index.tsx
  src/pages/products-create/components/ReservationCardInfo/ReservationCardInfo.style.tsx
  src/pages/products-create/components/ReservationCardInfo/index.tsx
  src/pages/products-create/delete/ProductDelete.style.tsx
  src/pages/products-create/delete/index.tsx
  src/pages/products-create/rejection-reason/RejectionReason.style.tsx
  src/pages/products-create/rejection-reason/index.tsx
  src/pages/products-create/reservation-details/ReservationDetails.style.tsx
  src/pages/products-create/reservation-details/index.tsx
  src/pages/products-create/reservations/ProductReservations.style.tsx
  src/pages/products-create/reservations/index.tsx
Labels: ✨ Feature

#229 코드리뷰 적용 안된부분 수정
  src/pages/reservation/reserve/index.tsx
Labels: 🔥 Fix, 🔨 Refactor

#251 예약하기 버튼 가려지는 현상 수정 & 체크 박스 수정 & discount 제거
  src/components/footer-reservation/FooterReservation.style.tsx
  src/components/footer-reservation/FooterReservation.type.ts
  src/components/footer-reservation/index.tsx
  src/components/product-card/ProductCard.style.tsx
  src/components/product-card/ProductCard.type.ts
  src/components/product-card/ProductCardSkeleton.tsx
  src/components/product-card/index.tsx
  src/constants/MOCK_DATA.ts
  src/pages/mypage/dummyData.json
  src/pages/mypage/my-product-list/index.tsx
  src/pages/products-detail/components/product-review/review/index.tsx
  src/pages/products-detail/index.tsx
  src/pages/products-detail/mockData.ts
  src/pages/reservation/reserve/index.tsx
  src/pages/reservation/reserved-detail/index.tsx
  src/utils/registerLocalStorage.ts
Labels: 🔥 Fix, 🔨 Refactor, 🎨 UI

#254 #226 PR 타입 오류 수정
  src/assets/common/defaultImage.png
  src/pages/products-detail/components/product-review/review/ReviewPage.tsx
  src/pages/products-detail/components/product-review/review/index.tsx
  src/store/product-slice/product-slice.type.ts
Labels: 🔥 Fix

#256 fix: 타입 오류 수정
  src/components/calendar-input/CalendarInput.type.ts
  src/pages/reservation/components/reservation-input/Reservation.type.ts
  src/pages/reservation/components/sheet/calendar-sheet/index.tsx
  src/pages/review/components/comment-card/index.tsx
  src/pages/review/detail/index.tsx
  src/store/product-slice/product-slice.type.ts
Labels: 🔥 Fix

#260 reissue 401 에러 해결
  src/utils/tokenStorage.ts
Labels: 🔥 Fix

#257 상품 등록
  package-lock.json
  package.json
  src/api/productsAPI.ts
  src/components/blur-sheet/BlurSheet.style.tsx
  src/components/blur-sheet/index.tsx
  src/components/bottom-sheet/BottomSheet.style.tsx
  src/components/calendar-input/CalendarInput.type.ts
  src/components/calendar-input/index.tsx
  src/components/footer-button/index.tsx
  src/components/input/index.tsx
  src/components/sheet-header/SheetHeader.type.ts
  src/constants/API.ts
  src/constants/FILTERING_BROWSING.ts
  src/pages/mypage/components/edit-password/EditPasswordPage.style.tsx
  src/pages/mypage/edit/MyPageEditPage.style.tsx
  src/pages/mypage/edit/index.tsx
  src/pages/mypage/exit-verification/ExitVerification.style.tsx
  src/pages/mypage/exit/index.tsx
  src/pages/products-create/ProductsCreate.type.ts
  src/pages/products-create/ProductsCreatePage.style.tsx
  src/pages/products-create/index.tsx
  src/pages/review/write/ReviewWritePage.style.tsx
  src/pages/review/write/index.tsx
  src/pages/signup/index.tsx
  src/types/postProductData.type.ts
Labels: ✨ Feature, 📬 API

#262 Choi/squad b fix
  kakao.d.ts
  src/api/productsAPI.ts
  src/components/calendar-input/CalendarInput.styles.tsx
  src/components/calendar-input/CalendarInput.type.ts
  src/components/calendar-input/index.tsx
  src/components/footer-reservation/FooterReservation.type.ts
  src/components/footer-reservation/index.tsx
  src/components/search-input/index.tsx
  src/components/search-sheet/PopularSearch.tsx
  src/components/search-sheet/SearchSheet.type.ts
  src/components/search-sheet/index.tsx
  src/constants/API.ts
  src/hooks/api/productsAPI/useGetTopKeyword.ts
  src/hooks/api/productsAPI/useProductCardsParams.ts
  src/pages/products-detail/components/product-info/index.tsx
  src/pages/products-detail/index.tsx
  src/pages/products/components/filtering-sheet/index.tsx
  src/pages/reservation/components/sheet/calendar-sheet/CalendarSheet.styles.tsx
  src/pages/reservation/components/sheet/calendar-sheet/index.tsx
  src/pages/reservation/components/sheet/pay-confirm-sheet/index.tsx
  src/pages/reservation/reserve/ReservationPage.style.tsx
  src/pages/reservation/reserve/index.tsx
  src/store/reservation-slice/reservation-slice.ts
  src/store/reservation-slice/reservation-slice.type.ts
  src/store/store.ts
  src/styles/GlobalStyles.tsx
  src/types/getMemberData.type.ts
  src/utils/dateValueBetween.ts
  src/utils/kakaoShare.ts
  src/utils/shuffleArray.ts
Labels: ✨ Feature, 🔥 Fix, 📬 API, 🔨 Refactor

#264 후기 데이터 연결, 페이지네이션, 상세 설명 연결
  src/api/reviewAPI.ts
  src/constants/API.ts
  src/hooks/api/productsAPI/useProductDetail.ts
  src/hooks/api/reviewAPI/useGetReviews.ts
  src/hooks/api/reviewAPI/useLoadMoreReviews.ts
  src/pages/products-create/reservation-details/ReservationDetails.style.tsx
  src/pages/products-create/reservation-details/index.tsx
  src/pages/products-detail/ProductsDetail.style.tsx
  src/pages/products-detail/components/description/Description.type.ts
  src/pages/products-detail/components/description/index.tsx
  src/pages/products-detail/components/load-more-button/index.tsx
  src/pages/products-detail/components/product-review/index.tsx
  src/pages/products-detail/components/product-review/review/Review.style.tsx
  src/pages/products-detail/components/product-review/review/ReviewImages.tsx
  src/pages/products-detail/components/product-review/review/index.tsx
  src/pages/products-detail/index.tsx
  src/types/review.type.ts
Labels: ✨ Feature, 🔨 Refactor

#263 Yohan/squad b UI
  src/components/navigate-button/index.tsx
  src/components/product-header/ProductHeader.type.ts
  src/components/product-header/index.tsx
  src/pages/products/index.tsx
  src/pages/reservation/components/reservation-input/ReservationInput.style.tsx
  src/pages/reservation/reserve/ReservationPage.style.tsx
Labels: 🔥 Fix

#265 타입 및 빌드 오류 해결
  src/components/search-input/RecommendedSearches.tsx
Labels: 🔥 Fix

#267 reissue 에러 해결
  src/hooks/useLogout.ts
  src/pages/mypage/edit/index.tsx
  src/pages/signup/index.tsx
  src/utils/tokenStorage.ts
Labels: 🔥 Fix, 🔨 Refactor

#266 상세 상품 페이지 리뷰 에러 해결
  src/components/product-card/index.tsx
  src/hooks/api/reviewAPI/useGetReviews.ts
  src/hooks/api/reviewAPI/useLoadMoreReviews.ts
  src/pages/products-detail/components/product-info/index.tsx
  src/pages/products-detail/components/product-review/index.tsx
  src/pages/products-detail/components/product-review/review/Review.type.ts
  src/pages/products-detail/components/product-review/review/index.tsx
  src/pages/products-detail/index.tsx
  src/pages/review/list/index.tsx
  src/pages/review/write/index.tsx
Labels: 🔥 Fix

#272 트래블리 마이페이지
  src/Router.tsx
  src/api/myAPI.ts
  src/constants/API.ts
  src/constants/NAVIGATE_BUTTON.ts
  src/hooks/api/memberAPI/useGetProfileByRole.ts
  src/pages/bookmark/BookmarkPage.style.tsx
  src/pages/bookmark/index.tsx
  src/pages/chat/ChatPage.style.tsx
  src/pages/chat/index.tsx
  src/pages/mypage/components/dashboard/Dashboard.style.tsx
  src/pages/mypage/components/dashboard/Dashboard.type.ts
  src/pages/mypage/components/dashboard/index.tsx
  src/pages/mypage/components/my-product/index.tsx
  src/pages/mypage/components/profile-tab/index.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/my-product-list/index.tsx
  src/pages/review/list/ReviewList.style.tsx
  src/pages/review/list/index.tsx
  src/types/getMemberData.type.ts
  src/utils/formatWIthCommas.ts
Labels: 📬 API

#274 vite.config.ts 파일 관련 빌드 에러 수정
  tsconfig.json
Labels: 🌏 Deploy, 🔥 Fix

#275 에러 페이지
  src/Router.tsx
  src/api/instance.ts
  src/assets/common/fire.png
  src/assets/common/no-product.png
  src/components/page-header/index.tsx
  src/pages/error/Error404Page.tsx
  src/pages/error/Error500Page.tsx
  src/pages/error/ErrorPage.style.tsx
  src/pages/error/NoProductPage.tsx
  src/pages/products-detail/index.tsx
Labels: ✨ Feature, 🎨 UI

#278 트래블러(구매자) 마이페이지
  package-lock.json
  package.json
  src/api/instance.ts
  src/api/myAPI.ts
  src/hooks/useLogout.ts
  src/pages/mypage/dummyData.json
  src/pages/mypage/index.tsx
Labels: 📬 API

#280 상세 페이지 후기 정렬 기능 추가 및 오류 개선, 후기 케밥 버튼 버블링 방지
  src/constants/FILTERING_BROWSING.ts
  src/hooks/api/productsAPI/useProductDetail.ts
  src/hooks/api/reviewAPI/useGetReviews.ts
  src/hooks/api/reviewAPI/useLoadMoreReviews.ts
  src/pages/products-detail/components/product-review/review/Review.style.tsx
  src/pages/products-detail/components/product-review/review/ReviewPage.tsx
  src/pages/products-detail/components/product-review/review/index.tsx
  src/pages/products-detail/components/review-order-sheet/ReviewOrderSheet.type.ts
  src/pages/products-detail/components/review-order-sheet/index.tsx
  src/pages/products-detail/components/sheet-renderer/SheetRenderer.type.ts
  src/pages/products-detail/components/sheet-renderer/index.tsx
  src/pages/products-detail/index.tsx
  src/pages/products/components/card-orders-sheet/index.tsx
Labels: ✨ Feature, 🔥 Fix, 🔨 Refactor

#273 리뷰보기 버튼, 인기상품 조회
  src/api/productsAPI.ts
  src/constants/API.ts
  src/hooks/api/productsAPI/useGetTopProductsQuery.ts
  src/pages/home/index.tsx
  src/pages/products-detail/components/product-info/index.tsx
  src/pages/products-detail/components/product-info/info/Info.type.ts
  src/pages/products-detail/components/product-info/info/index.tsx
  src/pages/products-detail/components/product-review/index.tsx
  src/pages/products-detail/components/product-review/review/Review.type.ts
  src/pages/products-detail/components/product-review/review/index.tsx
  src/pages/products-detail/index.tsx
  src/types/getProductData.type.ts
Labels: ✨ Feature, 📬 API

#281 시트에 자잘한 애니메이션 추가
  src/components/category-section/CategorySection.style.tsx
  src/components/grab-sheet/GrabSheet.style.tsx
  src/components/layout/Layout.style.tsx
  src/components/navigate-button/NavigateButton.style.tsx
  src/styles/GlobalStyles.tsx
Labels: ✨ Feature

#282 판매자 마이페이지, 상품 수량 등록
  src/api/instance.ts
  src/api/myAPI.ts
  src/api/reviewAPI.ts
  src/components/product-card/ProductCard.type.ts
  src/components/product-card/index.tsx
  src/components/review-product-card/index.tsx
  src/constants/API.ts
  src/constants/FILTERING_BROWSING.ts
  src/hooks/api/memberAPI/useGetTravellyReview.ts
  src/pages/products-create/index.tsx
  src/pages/review/list/index.tsx
  src/pages/review/write/index.tsx
  src/types/getMemberData.type.ts
  src/types/review.type.ts
Labels: 🔥 Fix, 📬 API

#286 모바일 환경을 고려한 페이지 height 수정
  src/components/layout/Layout.style.tsx
  src/pages/home/HomePage.style.tsx
Labels: 🔥 Fix

#287 모바일 환경을 고려한 footer와 sheet 수정
  src/components/bottom-sheet/BottomSheet.style.tsx
  src/components/footer-navigation/FooterNavigation.style.tsx
  src/components/grab-sheet/GrabSheet.style.tsx
Labels: 🔥 Fix

#288 후기 작성
  src/api/reviewAPI.ts
  src/components/review-product-card/index.tsx
  src/pages/products-detail/index.tsx
  src/pages/review/detail/index.tsx
  src/pages/review/write/index.tsx
Labels: 🔥 Fix

#292 이메일 비밀번호 찾기
  src/Router.tsx
  src/api/authAPI.ts
  src/assets/common/key.svg
  src/constants/API.ts
  src/pages/products-create/rejection-reason/RejectionReason.style.tsx
  src/pages/recovery/Recovery.style.tsx
  src/pages/recovery/components/email-result/EmailRecoveryResult.style.tsx
  src/pages/recovery/components/email-result/EmailRecoveryResult.type.ts
  src/pages/recovery/components/email-result/index.tsx
  src/pages/recovery/components/email-search/EmailRecoverySearch.style.tsx
  src/pages/recovery/components/email-search/EmailRecoverySearch.type.ts
  src/pages/recovery/components/email-search/index.tsx
  src/pages/recovery/components/password-result/PasswordRecoveryResult.style.tsx
  src/pages/recovery/components/password-result/index.tsx
  src/pages/recovery/components/password-search/PasswordRecoverySearch.style.tsx
  src/pages/recovery/components/password-search/PasswordRecoverySearch.type.ts
  src/pages/recovery/components/password-search/index.tsx
  src/pages/recovery/email-recovery/EmailRecovery.style.tsx
  src/pages/recovery/email-recovery/index.tsx
  src/pages/recovery/index.tsx
  src/pages/recovery/password-recovery/PasswordRecovery.style.tsx
  src/pages/recovery/password-recovery/index.tsx
  src/pages/signup/index.tsx
  src/utils/handleLogin.ts
  src/utils/isAxiosError.ts
Labels: ✨ Feature

#293 예약 상세 인원 api 연결 & 리뷰 카드 오류 해결
  src/assets/react.svg
  src/components/footer-reservation/FooterReservation.style.tsx
  src/components/review-product-card/index.tsx
  src/hooks/api/reserveAPI/reservation.type.ts
  src/pages/reservation/components/ticket-count-section/ReserveTicket.tsx
  src/pages/reservation/components/ticket-count-section/ReservedTicket.tsx
  src/pages/reservation/components/ticket-count-section/TicketCountSection.style.tsx
  src/pages/reservation/components/ticket-count-section/TicketCountSection.type.ts
  src/pages/reservation/components/ticket-count-section/index.tsx
  src/pages/reservation/reserved-detail/ReservedDetailPage.styles.tsx
  src/pages/reservation/reserved-detail/index.tsx
Labels: 🔥 Fix, 📬 API

#295 배포 환경에서 카카오맵 마커가 나타나지 않는 현상 수정
  public/marker.svg
  src/hooks/useKakaoMap.ts
Labels: 🔥 Fix

#298 상품 삭제하기
  src/api/productsAPI.ts
  src/assets/common/delete.svg
  src/components/footer-edit-delete/FooterEditDelete.style.tsx
  src/components/footer-edit-delete/index.tsx
  src/pages/products-detail/index.tsx
Labels: ✨ Feature

#301 트래블러 마이페이지 - 예약 리스트 페이지 연결
  src/pages/mypage/components/dashboard/index.tsx
  src/pages/reservation/reserved-list/index.tsx
  src/pages/review/detail/dummyData.json
Labels: ✨ Feature

#303 review-product-card 임시 오류 수정 & productDetail 데이터 전송 방식 변경 & padding-bottom 추가
  src/components/footer-reservation/FooterReservation.type.ts
  src/components/footer-reservation/index.tsx
  src/components/review-product-card/ReviewProductCard.type.ts
  src/components/review-product-card/index.tsx
  src/pages/home/HomePage.style.tsx
  src/pages/products-create/reservations/ProductReservations.style.tsx
  src/pages/products-create/reservations/index.tsx
  src/pages/products-detail/ProductsDetail.style.tsx
  src/pages/products-detail/components/load-more-button/index.tsx
  src/pages/products-detail/components/product-review/review/ReviewPage.tsx
  src/pages/products-detail/components/product-review/review/index.tsx
  src/pages/products-detail/index.tsx
  src/pages/reservation/reserve/ReservationPage.style.tsx
  src/pages/reservation/reserve/index.tsx
  src/pages/review/detail/index.tsx
  src/pages/review/list/index.tsx
Labels: 🔥 Fix, 🔨 Refactor

#305 fix: select-plan 배포 환경에서 이미지 깨짐 #304
  src/pages/login/components/bubble/Bubble.type.ts
  src/pages/login/components/bubble/index.tsx
Labels: 🔥 Fix

#306 fix: 재로그인 alert 여러번 뜨는 이슈 #268
  src/hooks/useLogout.ts
  src/pages/mypage/edit/index.tsx
Labels: 🔥 Fix

#307 알림 페이지 #233
  src/Router.tsx
  src/assets/home/alert.svg
  src/components/header/index.tsx
  src/pages/mypage/index.tsx
  src/pages/noti/NotiPage.style.tsx
  src/pages/noti/index.tsx
  src/pages/noti/noti-card/NotiCard.style.tsx
  src/pages/noti/noti-card/index.tsx
Labels: ✨ Feature

#309 feat: url
  index.html
Labels: 📃 Docs

#311 fix: 오픈그래프 이미지 안 뜸
  index.html
Labels: 🔥 Fix

#312 브라우징 페이지 이미지 배너 적용
  package-lock.json
  package.json
  src/assets/home/banner-picnic.png
  src/assets/home/banner-sky.png
  src/assets/home/left-arrow.svg
  src/assets/home/right-arrow.svg
  src/pages/home/Banner.tsx
  src/pages/home/HomePage.style.tsx
  src/pages/home/index.tsx
Labels: ✨ Feature

#318 판매자 - 예약 관리 리스트
  src/Router.tsx
  src/api/reservation.ts
  src/constants/API.ts
  src/hooks/api/reserveAPI/reservation.type.ts
  src/hooks/api/reserveAPI/useGetReservationManage.ts
  src/pages/mypage/components/dashboard/index.tsx
  src/pages/products-create/ProductsCreatePage.style.tsx
  src/pages/reservation/components/reservation-card/ReservationCard.style.tsx
  src/pages/reservation/components/reservation-card/index.tsx
  src/pages/reservation/manage-detail/index.tsx
  src/pages/reservation/manage-list/Manage.style.tsx
  src/pages/reservation/manage-list/index.tsx
Labels: ✨ Feature

#321 후기 상세 데이터 깨짐 해결
  src/constants/API.ts
  src/hooks/api/memberAPI/useGetReview.ts
  src/pages/mypage/components/dashboard/index.tsx
  src/pages/mypage/edit/MyPageEditPage.style.tsx
  src/pages/mypage/edit/index.tsx
  src/pages/mypage/index.tsx
  src/pages/products-detail/components/product-review/review/index.tsx
  src/pages/review/list/index.tsx
  src/utils/makeKORLocale.ts
Labels: 🔥 Fix

#322 판매자 받은 후기 데이터 깨지는 문제
  src/components/footer-edit-delete/FooterEditDelete.style.tsx
  src/components/review-product-card/index.tsx
  src/pages/products-detail/components/product-review/review/Review.type.ts
  src/pages/reservation/components/reservation-card/ReservationCard.style.tsx
  src/pages/reservation/components/reservation-card/index.tsx
  src/pages/review/list/index.tsx
  src/store/product-slice/product-slice.type.ts
Labels: 🔥 Fix

#327 banner 높이 고정 삭제
  src/pages/home/Banner.tsx
Labels: 🔥 Fix

#328 배너 인디케이터 bottom 값 변경
  src/pages/home/Banner.tsx
Labels: 🔥 Fix

#329 wip: 에러 때문에 일단 막아둠
  src/pages/review/list/index.tsx
Labels: 🔥 Fix

#330 예약관리 api연결
  src/Router.tsx
  src/api/reservation.ts
  src/constants/API.ts
  src/hooks/api/reserveAPI/reservation.type.ts
  src/pages/products-create/components/ReservationCard/ReservationCard.type.ts
  src/pages/products-create/components/ReservationCard/index.tsx
  src/pages/products-create/components/ReservationCard/mockData.ts
  src/pages/products-create/components/ReservationCardButtonContainer/index.tsx
  src/pages/products-create/rejection-reason/index.tsx
  src/pages/products-create/reservation-details/ReservationDetails.style.tsx
  src/pages/products-create/reservation-details/index.tsx
  src/pages/reservation/components/ManageCard/ManageCard.style.tsx
  src/pages/reservation/components/ManageCard/ManageCard.type.ts
  src/pages/reservation/components/ManageCard/index.tsx
  src/pages/reservation/components/ManageCardButtonContainer/ManageCardButtonContainer.style.ts
  src/pages/reservation/components/ManageCardButtonContainer/ManageCardButtonContainer.type.ts
  src/pages/reservation/components/ManageCardButtonContainer/index.tsx
  src/pages/reservation/components/ManageCardInfo/ManageCardInfo.style.tsx
  src/pages/reservation/components/ManageCardInfo/index.tsx
  src/pages/reservation/components/ticket/Ticket.style.tsx
  src/pages/reservation/components/ticket/index.tsx
  src/pages/reservation/manage-detail/ManageDetail.style.tsx
  src/pages/reservation/manage-detail/index.tsx
  src/pages/reservation/rejection-reason/RejectionReason.style.tsx
  src/pages/reservation/rejection-reason/index.tsx
Labels: ✨ Feature, 📬 API
